version: '3'
services:
  pg-master:
    image: postgres:9.6

    container_name: postgresql-master
    environment:
      POSTGRES_PASSWORD: qqw@1024
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

